/*
 * Auto-generated root-level exports for docker-types package v1.48.3
 * This file re-exports all types from Docker API version 1.48
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-root-index.js
 */

export * from './generated/1.48/index';
