/*
 * Auto-generated root-level exports for docker-types package v1.56.0
 * This file re-exports all types from Docker API version 1.56
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-root-index.js
 */

export * from './generated/1.56/index.ts';
